### ISSUE TITLE
with the extension a login is no longer possible

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-password-validation#6] opened 2020-08-24 14:53 UTC
If the extension is installed and you create a new PW in the BE, you cannot log in with it.

Contao 4.9.5

related with #3

**Comment by Toflar** [comment] 2020-08-26 07:20
@richardhj is this a duplicate of #3 aka going to be fixed in Contao core? If so, please close this :) Thx

**Comment by richardhj** [comment] 2020-08-27 15:27
I found an incompatibility when using PHP>=7.4.

> 7.4.0 | The values of the password algo IDs (PASSWORD_BCRYPT, PASSWORD_ARGON2I, PASSWORD_ARGON2ID and PASSWORD_DEFAULT) are now strings. Previously, they have been integers.

Fixed in 0d40143e8839c213b1b2c35bb0a68cfc47eb99b9.

**Closed as completed by richardhj** 2020-08-27 15:27 UTC

**Comment by zonky2** [comment] 2020-08-28 05:44
O.K. - I had PHP 7.2
